In [ ]:
import numpy as np
#pip install numpy

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


#Python List VS NumPy Arrays

1. NumPy arrays are faster (optimized in C)
2. NumPy stores dat ain continuous memory blocks
3. Uses less memory
4. Build-in mathematical features
5. Supports direct vectorized operations

In [ ]:
import time

In [ ]:
size = 100_00_000

#time
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
#vectorization
sq_arr = np_arr**2
end = time.time()
print(f"numpy array time = {end-start} seconds")


python list time = 0.7466554641723633 seconds
numpy array time = 0.03223133087158203 seconds


In [ ]:
#memory
import sys

In [ ]:
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
numpy array size = 80000000 bytes


its because python stores metadata as well


#Create - from lists

In [ ]:
arr1 = np.array([1,2,3,4,5])
print(arr1, type(arr1), arr1.dtype, arr1.shape)

arr2 = np.array([1,2,3,4,5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D, type(arr2D), arr2D.dtype, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [ ]:
#create from scratch
arr1 = np.zeros((2,3), dtype="int64") #prefill with 0s
print(arr1, arr1.shape)

arr2 = np.ones((2,3), dtype="int64") #prefill with 1s
print(arr2, arr2.shape)

arr3 = np.full((2,3), 100, dtype="int64") #prefill with 100s
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1,11, 2) #(start, stop ,step) , range elements
print(arr5, arr5.shape)

arr4 = np.linspace(1, 100, 3) # evenly spaced arrays (start , stop , space)
print(arr4, arr4.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.   50.5 100. ] (3,)


In [ ]:
#properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape) #dimensions = m x n
print(arr.size) #total elements
print(arr.ndim) #number of dimensions
print(arr.dtype) #data type

float_arr = arr.astype(np.float64) #type casting ie. changing data type
print(float_arr, float_arr.dtype)

(3, 3)
9
2
int64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


## OPERATIONS ON NUMPY
1. Reshape
2. Indexing (accessing values through index)
3. Fancy & Boolean indexing
4. Slicing

In [ ]:
#reshaping
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped_arr = arr.reshape((3,2))
print(reshaped_arr, reshaped_arr.shape)

flattened_arr = arr.flatten() #2d into 1d
print(flattened_arr, flattened_arr.shape)

transposed_arr = arr.T
print(transposed_arr, transposed_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)
[[1 4]
 [2 5]
 [3 6]] (3, 2)


In [ ]:
#indexing
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[-1])
print(arr[1:4])

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D[0,0]) #(row, column)
print(arr2D[0,1])

#fancy indexing
idx = [0,1,3]
print(arr[idx])

#boolean indexing (based on condition if true it returns that value)
print(arr[arr > 2])
print(arr[arr % 2 == 0]) #even no.
print(arr[arr % 2 != 0]) #odd no.

1
5
[2 3 4]
1
2
[1 2 4]
[3 4 5]
[2 4]
[1 3 5]


In [ ]:
#slicing [start, stop, step]
arr = np.array([1,2,3,4,5])

print(arr[1:4])
print(arr[1:])
print(arr[:1])
#in py it creates the copy of slice but in numpy it creates a view

[2 3 4]
[2 3 4 5]
[1]


In [ ]:
#copy vs view

#copy in python
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 100
print(sub_list)
print(nums)

[2, 3]
[100, 3]
[1, 2, 3, 4, 5]


In [ ]:
#view in numpy
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 100
print(sub_arr)
print(arr)

#to make copy of arr using numpy use .copy()
arr2 = np.array([1,2,3,4,5])
sub_arr2 = arr2[1:3].copy() #it maskes copy of view
print(sub_arr2)
sub_arr2[0] = 100
print(sub_arr2)

[2 3]
[100   3]
[  1 100   3   4   5]
[2 3]
[100   3]


## Common Data Type
1. integers: int32, int64
2. floating point nums: float32, float64
3. boolean: bool
4. complex nums: complex64, complex128
5. string: S(byte-str) & U(unicode-str)
6. object: generic python objects - object

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

arr2 = np.array([1.0,2.0,3.0,4.0,5.0])
print(arr2.dtype)

arr3 = np.array([3 + 5j])
arr4 = np.array([4 + 6j])
print(arr3, arr3.dtype)
print(arr3 + arr4)
print(arr4 - arr3)

arr5 = np.array(["hello", {1,2,3}, 3.14])
print(arr5, arr5.dtype)

int64
float64
[3.+5.j] complex128
[7.+11.j]
[1.+1.j]
['hello' {1, 2, 3} 3.14] object


#Axes in muilti- dimensional array
eg. images are stored in form of nos
* blabk and white img: stored in 2D array
* colored img: stored in RGB ie red-green-blue (eg. for red color its (255,0,0)) in form of 3D array

##Axes:
* 1D array: 1 axis (0)
* 2D array: 2 axes (0 for rows , 1 for columns)
* 3D array: 3 axes(0 for depth/layers, 1 for rows in each layer, 2 for columns)

In [ ]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))

SUM_OF_COLS = np.sum(arr2D, axis=0)
print(SUM_OF_COLS)

SUM_OF_ROWS = np.sum(arr2D, axis=1)
print(SUM_OF_ROWS)

print(arr2D[0:2,1:2])#Slicing

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [ ]:
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D, arr3D.shape) #2 X 3 X 2

#indexing
print(arr3D[0,1,1])

#slicing
print(arr3D[:,0,:]) #first row from both layers
print(arr3D[:,:,0]) #first col from both layers

arr3D[:,0,:] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


#Vectorization and Broadcasting
<b>1. Vectorization</b>: It is the process of applying operations to entire arrays or sequences of data at once, rather than iterating through individual elements using explicit loops.

<b>2. Broadcasting</b>: It is a mechanism that allows NumPy to perform operations on arrays of different shapes without explicitly reshaping them (creating copies of the smaller array to match the larger array's shape).

<b> Broadcasting Condition <b>

For broadcasting to happen the dimensions should be compatible. Numpy compares shape element-wise. It starts dimension comparison with the trailing (i.e. rightmost) dimension and works its way left.
Two dimensions are compatible when <ol> <li>they are equal, or</li> <li>one of them is 1. </li>

In [ ]:
#vectorization

arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr ** 2)
print(arr + 2)
print(arr * 2)
print(arr + arr2)

#broadcasting (scaling)
arr3 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr.shape)
print(arr3.shape)

print(arr + arr3)

[ 1  4  9 16 25]
[3 4 5 6 7]
[ 2  4  6  8 10]
[ 7  9 11 13 15]
(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


#Vector normalization used in ML
* std normatization

   (arr - mean)/SD

In [ ]:
#normalization
arr = np.array([[1,2],[3,4]])
print(np.mean(arr)) #mean
print(np.std(arr)) #standard deviation

print((arr - np.mean(arr))/np.std(arr)) #std normalization


2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


#Mathematiccal functions

1. Aggregation functions
   - sum()
   - prod()
   - min() & argmin() - min val & idx of min val
   - max() & argmax() - max val & idx of max val
   - mean()
   - median()
   - std() - standard deviation
   - var() - variance

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) #returns index
print(np.argmax(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
2.0


2. Power functions
   - square()
   - sqrt() - square root
   - pow(a, b) - a^b

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


3. Log & Exponential functions
   - log() - natual log
   - log10() - log base 10
   - log2() - log base 2
   - exp() - exponentional i.e. e^x

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


4. Rounding functions
   - round() - rounds to nearest value
   - floor() - rounds down
   - ceil() - rounds up
   - trunc() - truncates decimal part

In [ ]:
print(np.round(3.14))
print(np.floor(3.14))
print(np.ceil(3.14))
print(np.trunc(3.14))

3.0
3.0
4.0
3.0


5. Additional functions
   - abs() - absolute value
   - sort()
   - unique() - returns unique values

In [ ]:
arr = np.array([1,2,3,4,5,5,8,-9,-10])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr)) #absolute values ie make -ve values +ve

[-10  -9   1   2   3   4   5   8]
[-10  -9   1   2   3   4   5   5   8]
[ 1  2  3  4  5  5  8  9 10]
