In [ ]:
import numpy as np

Create an array

In [ ]:
a = np.array([10,20,30,40,50])

Add 1 to every age

In [ ]:
emp_age = np.array([22,25,28,31,35])
emp_age = emp_age + 1
print(emp_age)

[23 26 29 32 36]


10% hike on current salary

In [ ]:
salary = np.array([5,7,9,11])
new_salary = salary + (salary * 0.1)
print(new_salary)

[ 5.5  7.7  9.9 12.1]


shape , size , dtype

In [ ]:
data = np.array([100, 200, 300, 400, 500])
print(data.size)
print(data.shape)
print(data.dtype)

5
(5,)
int64


In [ ]:
emp = np.array([
    [22,5],
    [25,7],
    [30,10],
    [35,15]
])
print(emp.size)
print(emp.shape)
print(emp.dtype)
print(emp.ndim)

8
(4, 2)
int64
2


In [ ]:
print(emp[0,:])
print(emp[-1,:])
print(emp[:,0])
print(emp[:,-1])
print(emp[:2,:])
print(emp[-2:,:])

[22  5]
[35 15]
[22 25 30 35]
[ 5  7 10 15]
[[22  5]
 [25  7]]
[[30 10]
 [35 15]]


Concept 1 — Comparison Operators

In [ ]:
salary = np.array([5,7,10,15])

print(salary >= 10) #result - Boolean Mask

[False False  True  True]


Concept 2 — Boolean Indexing

In [ ]:
salary = np.array([5,7,10,15])

print(salary[salary >= 10])

[10 15]


In [ ]:
emp = np.array([
    [22,5],
    [25,7],
    [30,10],
    [35,15]
])

salary = emp[:,1] #extract salary
print(salary)
print(salary[salary >= 10]) #find emps earning at least Rs. 10 LPA

[ 5  7 10 15]
[10 15]
37
9.25
5
15
3.766629793329841


aggregation functions

In [ ]:
print(salary.sum()) #Aggregation: sum
print(salary.mean()) #Aggregation: avg
print(salary.min()) #Aggregation: min
print(salary.max()) #Aggregation: max
print(salary.std()) #Aggregation: std

37
9.25
5
15
3.766629793329841


math operations

In [ ]:
salary = salary * 1.10 #increase salary by 10%
print(salary)

[ 6.05  8.47 12.1  18.15]


In [ ]:
salary = salary + 2 #bonus
print(salary)

[ 8.05 10.47 14.1  20.15]


In [ ]:
salary = salary - 1 #tax deduction
print(salary)

[ 7.05  9.47 13.1  19.15]


In [ ]:
age = emp[:,0]
salary = emp[:,1]

print((age > 25) & (salary > 8))

[False False  True  True]


In [ ]:
print(emp[(age > 25) & (salary > 8)])

[[30 10]
 [35 15]]


In [ ]:
salary = np.array([4,6,8,10,12])
print(salary[(salary > 8) & (salary < 10)])

[]


In [ ]:
emp = np.array([
    [22,5],
    [25,7],
    [30,10],
    [35,15]
])
print(emp[emp[:,0] > 25])
print(emp[emp[:,1] > 7])
print(emp[(emp[:,0] > 25) & (emp[:,1] > 7)])

[[30 10]
 [35 15]]
[[30 10]
 [35 15]]
[[30 10]
 [35 15]]


In [ ]:
marks = np.array([55,72,81,95,48,67])
print(marks.mean())
print(marks.max())
print(marks.min())
print(marks[marks > marks.mean()])

69.66666666666667
95
48
[72 81 95]
